{{- if .Values.multi_cluster }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-sa
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
imagePullSecrets:
{{- if .Values.imageCredentials.create }}
- name: {{ .Release.Namespace }}-registry-secret
{{- else }}
- name: {{ .Values.imageCredentials.name }}
{{- end }}

{{- end }}
