{{- if not .Values.aquaCluster }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Namespace }}-sa
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ .Release.Namespace }}
{{- end }}
