apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aquaSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  token: {{ .Values.aquaSecret.kubeEnforcerToken | b64enc }}               # aqua kube enforcer token